### ISSUE TITLE
WIll you push to 1.19?

### ISSUE THREAD

**Issue by drakosoldier298** [Ayutac/tr-patchouli#4]
I hate being the guy of "update??"

just wondering if a 1.19 update is planned as this mod looks amazingly usefull

**Comment by Ayutac** [comment]
> I hate being the guy of "update??"

This is the right place for it though :)

When I was able to update, patchouli didn't yet, and then I had computer problems. Have a completely new setup now though.

Just need to figure out the migration process now

**Comment by Ayutac** [comment]
Done with 55d7395, should be available on CF shortly.

Thanks for opening a ticket, I might have forgotten otherwise ;)
